-- MySQL Script generated by MySQL Workbench
-- Saturday 25 March 2023 02:52:02 PM
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hawwkstore
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hawwkstore` ;

-- -----------------------------------------------------
-- Schema hawwkstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hawwkstore` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hawwkstore` ;

-- -----------------------------------------------------
-- Table `hawwkstore`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`orders` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`orders` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `price` DECIMAL(10,2) UNSIGNED NOT NULL,
  `date_of_order` DATE NULL DEFAULT NULL,
  `date_of_delivery` DATE NULL DEFAULT NULL,
  `mode_of_payment` ENUM('cash', 'upi', 'debit card', 'credit card', 'net banking') NULL DEFAULT 'cash',
  PRIMARY KEY (`id`),
  INDEX `date_of_order` (`date_of_order` ASC) VISIBLE,
  INDEX `date_of_delivery` (`date_of_delivery` ASC) VISIBLE,
  INDEX `mode_of_payment` (`mode_of_payment` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hawwkstore`.`active_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`active_orders` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`active_orders` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `raw_price` DECIMAL(10,2) UNSIGNED NOT NULL,
  `status` ENUM('ordered', 'ready', 'out for delivery', 'delivered') NULL DEFAULT 'ordered',
  PRIMARY KEY (`id`),
  INDEX `status` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_active_orders_to_orders`
    FOREIGN KEY (`id`)
    REFERENCES `hawwkstore`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hawwkstore`.`admin_team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`admin_team` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`admin_team` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `team_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `team_name` (`team_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hawwkstore`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`customers` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`customers` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `gender` ENUM('male', 'female') NULL DEFAULT 'male',
  `house_no` VARCHAR(100) NOT NULL,
  `locality` VARCHAR(100) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `state` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `first_name` (`first_name` ASC, `last_name` ASC) VISIBLE,
  INDEX `gender` (`gender` ASC) VISIBLE,
  INDEX `state` (`state` ASC, `city` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hawwkstore`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`category` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`category` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hawwkstore`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`product` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`product` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(100) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `cat_id` SMALLINT UNSIGNED NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `qty` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `specs` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `brand` (`brand` ASC) VISIBLE,
  INDEX `name` (`name` ASC) VISIBLE,
  INDEX `cat_id` (`cat_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_to_cat_id`
    FOREIGN KEY (`cat_id`)
    REFERENCES `hawwkstore`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hawwkstore`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`cart` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`cart` (
  `customer_id` SMALLINT UNSIGNED NOT NULL,
  `product_id` SMALLINT UNSIGNED NOT NULL,
  `qty` SMALLINT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`, `product_id`),
  INDEX `fk_cart_to_product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_to_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `hawwkstore`.`customers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cart_to_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `hawwkstore`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hawwkstore`.`customer_phone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`customer_phone` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`customer_phone` (
  `id` SMALLINT UNSIGNED NOT NULL,
  `phone` CHAR(10) NOT NULL,
  PRIMARY KEY (`id`, `phone`),
  CONSTRAINT `fk_customer_phone_to_customer`
    FOREIGN KEY (`id`)
    REFERENCES `hawwkstore`.`customers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hawwkstore`.`warehouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`warehouse` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`warehouse` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `phone` CHAR(10) NOT NULL,
  `plot_no` VARCHAR(100) NOT NULL,
  `locality` VARCHAR(100) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `state` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `name` (`name` ASC) VISIBLE,
  INDEX `state` (`state` ASC, `city` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hawwkstore`.`delivery_man`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`delivery_man` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`delivery_man` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `warehouse_id` SMALLINT UNSIGNED NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `phone` CHAR(10) NOT NULL,
  `status` ENUM('busy', 'available') NULL DEFAULT 'available',
  PRIMARY KEY (`id`),
  INDEX `warehouse_id` (`warehouse_id` ASC) VISIBLE,
  INDEX `first_name` (`first_name` ASC, `last_name` ASC) VISIBLE,
  INDEX `status` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_del_man_to_orders`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `hawwkstore`.`warehouse` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hawwkstore`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`employee` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`employee` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `admin_id` TINYINT UNSIGNED NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `gender` ENUM('male', 'female') NULL DEFAULT 'male',
  `phone` CHAR(10) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `admin_id` (`admin_id` ASC) VISIBLE,
  INDEX `first_name` (`first_name` ASC, `last_name` ASC) VISIBLE,
  INDEX `gender` (`gender` ASC) VISIBLE,
  CONSTRAINT `fk_empl_to_admin_team`
    FOREIGN KEY (`admin_id`)
    REFERENCES `hawwkstore`.`admin_team` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hawwkstore`.`manages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`manages` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`manages` (
  `table_name` VARCHAR(100) NOT NULL,
  `admin_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`table_name`, `admin_id`),
  INDEX `fk_manages_to_admin_team` (`admin_id` ASC) VISIBLE,
  CONSTRAINT `fk_manages_to_admin_team`
    FOREIGN KEY (`admin_id`)
    REFERENCES `hawwkstore`.`admin_team` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hawwkstore`.`map_active_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`map_active_orders` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`map_active_orders` (
  `order_id` SMALLINT UNSIGNED NOT NULL,
  `customer_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_map_active_orders_to_active_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `hawwkstore`.`active_orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_map_active_orders_to_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `hawwkstore`.`customers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hawwkstore`.`map_delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`map_delivery` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`map_delivery` (
  `order_id` SMALLINT UNSIGNED NOT NULL,
  `warehouse_id` SMALLINT UNSIGNED NOT NULL,
  `del_man_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `warehouse_id` (`warehouse_id` ASC) VISIBLE,
  INDEX `del_man_id` (`del_man_id` ASC) VISIBLE,
  CONSTRAINT `fk_map_delivery_to_del_man`
    FOREIGN KEY (`del_man_id`)
    REFERENCES `hawwkstore`.`delivery_man` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_map_delivery_to_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `hawwkstore`.`active_orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_map_delivery_to_warehouse`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `hawwkstore`.`warehouse` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hawwkstore`.`map_prev_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`map_prev_orders` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`map_prev_orders` (
  `customer_id` SMALLINT UNSIGNED NOT NULL,
  `order_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`customer_id`, `order_id`),
  INDEX `fk_map_prev_orders_to_orders` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_map_prev_orders_to_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `hawwkstore`.`customers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_map_prev_orders_to_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `hawwkstore`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hawwkstore`.`seller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`seller` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`seller` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `office_no` VARCHAR(100) NOT NULL,
  `locality` VARCHAR(100) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `state` VARCHAR(100) NOT NULL,
  `phone` CHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hawwkstore`.`map_sellers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`map_sellers` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`map_sellers` (
  `seller_id` SMALLINT UNSIGNED NOT NULL,
  `product_id` SMALLINT UNSIGNED NOT NULL,
  `qty` SMALLINT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`seller_id`, `product_id`),
  INDEX `fk_map_seller_to_product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_map_seller_to_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `hawwkstore`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_map_seller_to_seller_id`
    FOREIGN KEY (`seller_id`)
    REFERENCES `hawwkstore`.`seller` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hawwkstore`.`offers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`offers` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`offers` (
  `order_id` SMALLINT UNSIGNED NOT NULL,
  `discount` SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`order_id`, `discount`),
  CONSTRAINT `fk_offer_to_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `hawwkstore`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hawwkstore`.`order_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`order_item` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`order_item` (
  `product_id` SMALLINT UNSIGNED NOT NULL,
  `order_id` SMALLINT UNSIGNED NOT NULL,
  `qty` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  INDEX `fk_order_item_to_product` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_item_to_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `hawwkstore`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_item_to_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `hawwkstore`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hawwkstore`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`payment` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`payment` (
  `order_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_id` SMALLINT UNSIGNED NOT NULL,
  `date_of_payment` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  INDEX `date_of_payment` (`date_of_payment` ASC) VISIBLE,
  CONSTRAINT `fk_payment_to_customers`
    FOREIGN KEY (`customer_id`)
    REFERENCES `hawwkstore`.`customers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_payment_to_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `hawwkstore`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hawwkstore`.`verify_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hawwkstore`.`verify_orders` ;

CREATE TABLE IF NOT EXISTS `hawwkstore`.`verify_orders` (
  `order_id` SMALLINT UNSIGNED NOT NULL,
  `pin` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`order_id`),
  CONSTRAINT `fk_verify_orders_to_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `hawwkstore`.`active_orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
